version: '3.8'
services:
  db:
    image: mysql:5.7
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=devapi
      - MYSQL_USER=devapiuser
      - MYSQL_PASSWORD=devapipassword
      - MYSQL_ROOT_PASSWORD=ALKjal3kjylKJAylk3wjnylk
    ports:
      - '3306:3306'